### ISSUE TITLE
make tutorials/005_subtomogram_alignment.py working

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#12]

**Comment by ijinjay** [comment]
1. function `random_rotation_angle_zyz()` in file `geometry.ang_loc`  is missing.
2. function `align_vols_no_mask()` in file `align.util` is missing.
3. module `image.io` is missing.
4. function `save_png` in file `image.vol.util` is missing.

Pls fix. 😃 @xulabs

**Comment by xulabs** [comment]
@ijinjay functions added. save_png can be found in image.io

**Comment by ijinjay** [comment]
function `sphere_mask` in `model.util` is missing. 🌔 @xulabs

**Comment by xulabs** [comment]
Added. @ijinjay
