### ISSUE TITLE
implement saliency detection based particle picking

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#16]
According to 
Feature Decomposition Based Saliency Detection in Electron Cryo-Tomograms.
https://arxiv.org/abs/1801.10562

the supervoxel computation could be implemented on GPU using numba.

**Comment by xiangruz** [comment]
Bo Zhou said he lost the code.

**Comment by xulabs** [comment]
@xiangruz we can find a student to re-implement the method

**Comment by xulabs** [comment]
@zhuzhenxi please add code and tutorial under the following module
aitom.segmentation.saliency.feature_decomposition
