### ISSUE TITLE
Facing problem running ProtoNet

### ISSUE THREAD

**Issue by FromSaffronCity** [xulabs/aitom#199]
Greetings,

I am currently facing a problem whenever I try to work with [ProtoNet](https://github.com/xulabs/aitom/tree/master/aitom/classify/deep/supervised/cnn/few_shot/protonet). As per the documentation, if I run `python run_train.py`, I get the following error.

```
Traceback (most recent call last):
  File "run_train.py", line 4, in <module>
    from train import main
  File "/shared/home/v_ajmain_yasar_ahmed_sahil/aitom/aitom/classify/deep/supervised/cnn/few_shot/protonet/train.py", line 20, in <module>
    from protonets.utils import data as data_utils
  File "/shared/home/v_ajmain_yasar_ahmed_sahil/aitom/aitom/classify/deep/supervised/cnn/few_shot/protonet/protonets/utils/data.py", line 1, in <module>
    import protonets.data
ModuleNotFoundError: No module named 'protonets.data'
```

Apparently, there is no `protonets.data` file under the directory `protonets/utils` where the file `data.py` resides. Am I missing something here?

Thank you.

**Comment by xiangruz** [comment]
Is this resolved?

**Comment by FromSaffronCity** [comment]
The issue that I mentioned here was due to the absence of `protonet/protonets/data` directory in this Github repository. I am closing this issue now. But, the `aitom/aitom/classify/deep/supervised/cnn/few_shot/protonet` repository has not been updated yet. If it is not an issue, then I request you to update the particular repository. Thank you.
