### ISSUE TITLE
"tomominer_mbc" not found

### ISSUE THREAD

**Issue by ijinjay** [xulabs/aitom#2]
```python
import tomominer_mbc
```
in `faml.py` & `aitom/geometry/volume/hypervolume/util.py` raised error 
"No module named 'tomominer_mbc'"

module `aitom.filter.gaussian` has no attribute `dog_smooth__large_map`

Many `IndentationError` errors need to be fixed.

‼️  We should make a toy example to test the code as this week's objective. For example:

1. read mrc file using `io` module
2. filter the image with Guassian smoothing kernel.
3. align the data from different mrc files
4. other tasks.

😃

**Comment by xulabs** [comment]
Fixed
