### ISSUE TITLE
check autoencoder tutorial

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#20]
https://github.com/xulabs/aitom/blob/master/tutorials/006_autoencoder.py

**Comment by yg422** [comment]
Tutorial works as expected on keras 2.1.* (probably should add this to README if this is only intended to work with older versions of keras)

However with keras 2.2.* it generates the following error
`Traceback (most recent call last):
  File "006_autoencoder.py", line 90, in <module>
    SEG.decode_all_images(d, data_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aitom/classify/deep/unsupervised/autoencoder/seg_src.py", line 61, in decode_all_images
    autoencoder = KM.load_model(op_join(data_dir, 'model', 'model-autoencoder.h5'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/keras/engine/saving.py", line 258, in _deserialize_model
    .format(len(layer_names), len(filtered_layers))
ValueError: You are trying to load a weight file containing 7 layers into a model with 0 layers`

Possible cause of this error include:
1. the use of keras Input layer
2. the presence of the `input_shape` parameter in function calls to keras.layers
Please refer to [this issue](https://github.com/keras-team/keras/issues/10417) for more details

Another possible workaround is proposed [here](https://github.com/keras-team/keras/issues/11683). This workaround doesn't require changing the code line by line and add the additional parameter, but it seems a bit "hacky".

**Comment by xulabs** [comment]
hi @buptwhr can you check the problem detected by @yg422 ?

**Comment by buptwhr** [comment]
@yg422 I've noticed this problem, so I put keras==2.1.0 in requirements.txt. As for the issue you've mentioned, I read it before. But I don't know how to avoid Input or input_shape. 
By using `autoencoder.load_weights()` rather than `KM.load_model()`, I can  solve the problem. But there are so many `KM.load_model()` and `save_model` in the project. I am not sure it'a stable choice.
I suggest using keras==2.1.0 to make minimal change to the original code.
