### ISSUE TITLE
test deep learning based classification

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#22]
See if you can understand following tutorial and successfully run it

https://github.com/xulabs/aitom/blob/master/tutorials/010_deep_learning_subtomogram_classification.py

**Comment by yichuanyanyu26** [comment]
Test the subtomogram classification and successfully run on the Demo Dataset in 000_general.md
https://github.com/xulabs/aitom_doc/blob/master/tutorials/010_deep_learning_subtomogram_classification.py
