### ISSUE TITLE
integrate openset method into AITom

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#23]
write 10 - 20 slides and add to google drive, need to complete before Sep 15

---------------------------
The following tasks are not urgent, can be performed after the AAAI deadline

add the code under following module
aitom/aitom/classify/deep/supervised/cnn/openset

use existing functions in AITom as much as possible

write a tutorial and add to
https://github.com/xulabs/aitom_doc/blob/master/tutorials/011_openset_learning.py

prepare page and figures to be added to
https://github.com/xulabs/projects/openset_learning/readme.md

**Comment by d12306** [comment]
add the code for openset method in aitom/aitom/classify/deep/supervised/cnn/openset,

ready to write the tutorial.

**Comment by xulabs** [comment]
@d12306 please remember to also add tutorial and the readme.md into the folder
