### ISSUE TITLE
Make autoencoder working

### ISSUE THREAD

**Issue by xulabs** [xulabs/aitom#6]
add autoencoder code under

aitom.classify.deep.unsupervised.autoencoder

according to 
https://github.com/xulabs/projects/tree/master/autoencoder

and make it working.

write a tutorial on how to use it, and put the tutorial in
aitom/tutorials/006_autoencoder.py

**Comment by xulabs** [comment]
for development and debugging, can use simulated data generated by the following code
https://github.com/xulabs/aitom/blob/master/tutorials/003_simulate_subtomogram.py

**Comment by buptwhr** [comment]
https://github.com/xulabs/aitom/blob/bee4831e33905165108c4c96a2134eb5360231c5/aitom/classify/deep/unsupervised/autoencoder/seg_src.py#L56

function "decode_images" not found @xiangruz
