### ISSUE TITLE
`aitom.tomominer.image.util' not found

### ISSUE THREAD

**Issue by ijinjay** [xulabs/aitom#7]
In the first tutorial: 

https://github.com/xulabs/aitom/blob/master/tutorials/1.Load_volume_and_display.ipynb

Cannot use `aitom.image.vol.util.dsp_img` to display image.

Pls add `aitom.tomominer.image.util` to fix it.

**Comment by xulabs** [comment]
Fixed by adding aitom.image.util
Pls check
